#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""
Script to play back recorded positions on the Reachy Mini robot.

This script reads position data from a CSV file (generated by extract_positions.py)
and replays them on the Reachy robot with proper timing.
"""

import argparse
import asyncio
import csv
import sys
import time
from pathlib import Path

import numpy as np
from reachy_mini.reachy_mini import ReachyMini
from reachy_mini.utils import create_head_pose


def read_positions_from_csv(csv_file: str) -> list[dict]:
    """
    Read positions from a CSV file.

    Args:
        csv_file: Path to the CSV file containing position data

    Returns:
        List of position dictionaries with timestamp and position data
    """
    csv_path = Path(csv_file)
    if not csv_path.exists():
        print(f"Error: CSV file '{csv_file}' not found")
        sys.exit(1)

    positions = []
    with open(csv_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                position = {
                    "timestamp": row["timestamp"],
                    "time_ns": int(row["time_ns"]),
                    "body_angle": float(row["body_angle"]),
                    "r_antenna_angle": float(row["r_antenna_angle"]),
                    "l_antenna_angle": float(row["l_antenna_angle"]),
                    "head_position_x": float(row["head_position_x"]),
                    "head_position_y": float(row["head_position_y"]),
                    "head_position_z": float(row["head_position_z"]),
                    "head_rotation_roll": float(row["head_rotation_roll"]),
                    "head_rotation_pitch": float(row["head_rotation_pitch"]),
                    "head_rotation_yaw": float(row["head_rotation_yaw"]),
                }
                positions.append(position)
            except (ValueError, KeyError) as e:
                print(f"Warning: Skipping invalid row: {e}")
                continue

    return positions


async def play_positions(positions: list[dict]) -> None:
    """
    Play back positions on the Reachy robot.

    Args:
        positions: List of position dictionaries
    """
    if not positions:
        print("Error: No positions to play")
        return

    # Slice positions if needed
    print("Connecting to Reachy Mini...")

    with ReachyMini() as reachy:
        try:
            # Go to first position
            print("Moving to starting position...")
            first_pos = positions[0]
            head = create_head_pose(
                x=first_pos["head_position_x"] * 10,  # Convert cm to mm
                y=first_pos["head_position_y"] * 10,
                z=first_pos["head_position_z"] * 10,
                roll=first_pos["head_rotation_roll"],
                pitch=first_pos["head_rotation_pitch"],
                yaw=first_pos["head_rotation_yaw"],
                degrees=True,
                mm=True,
            )
            antennas = np.deg2rad(
                [first_pos["r_antenna_angle"], first_pos["l_antenna_angle"]]
            )
            body_yaw = np.deg2rad(first_pos["body_angle"])

            reachy.goto_target(
                head=head, antennas=antennas, body_yaw=body_yaw, duration=2.0
            )
            await asyncio.sleep(2.0)

            print("\n=== Starting playback ===")
            print(f"Playing {len(positions)} positions at 30 FPS")

            # Fixed frame rate: 30 FPS = 1/30 seconds per frame
            frame_duration = 1.0 / 30.0  # ~0.033 seconds

            for i, pos in enumerate(positions):
                frame_start_time = time.time()

                # Create head pose
                head = create_head_pose(
                    x=pos["head_position_x"] * 10,  # Convert cm to mm
                    y=pos["head_position_y"] * 10,
                    z=pos["head_position_z"] * 10,
                    roll=pos["head_rotation_roll"],
                    pitch=pos["head_rotation_pitch"],
                    yaw=pos["head_rotation_yaw"],
                    degrees=True,
                    mm=True,
                )
                antennas = np.deg2rad([pos["r_antenna_angle"], pos["l_antenna_angle"]])
                body_yaw = np.deg2rad(pos["body_angle"])

                try:
                    # Send position to robot
                    reachy.set_target(head=head, antennas=antennas, body_yaw=body_yaw)

                    # Progress indicator
                    if (i + 1) % 30 == 0 or i == len(positions) - 1:
                        progress = (i + 1) / len(positions) * 100
                        elapsed = (i + 1) * frame_duration
                        print(
                            f"Progress: {i + 1}/{len(positions)} "
                            f"({progress:.1f}%) - {elapsed:.1f}s elapsed"
                        )

                    # Wait for the remainder of the frame duration to maintain 30 FPS
                    frame_elapsed = time.time() - frame_start_time
                    sleep_time = frame_duration - frame_elapsed
                    if sleep_time > 0:
                        await asyncio.sleep(sleep_time)
                except ConnectionError as e:
                    print(f"Error: {e}")
                    print(
                        f"Error position: body_yaw={pos['body_angle']}, "
                        f"antennas={[pos['r_antenna_angle'], pos['l_antenna_angle']]}, "
                        f"head_translation=[{pos['head_position_x']}, "
                        f"{pos['head_position_y']}, {pos['head_position_z']}], "
                        f"head_rotation=[{pos['head_rotation_roll']}, "
                        f"{pos['head_rotation_pitch']}, {pos['head_rotation_yaw']}]"
                    )
                    sys.exit(1)

            print("Playback complete!")

            # Return to zero pose
            print("\nReturning to zero pose...")
            reachy.goto_target(
                head=np.eye(4), antennas=[0, 0], body_yaw=0, duration=2.0
            )
            await asyncio.sleep(2.0)

        except KeyboardInterrupt:
            print("\n\nPlayback interrupted by user")
            print("Returning to zero pose...")
            reachy.goto_target(
                head=np.eye(4), antennas=[0, 0], body_yaw=0, duration=2.0
            )
            await asyncio.sleep(2.0)

        print("Disconnected from Reachy Mini")


async def main():
    parser = argparse.ArgumentParser(
        description="Play back recorded positions on Reachy Mini robot at 30 FPS",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Play positions from a CSV file at 30 FPS
  python play_positions.py positions.csv
        """,
    )
    parser.add_argument(
        "csv_file",
        help="Path to the CSV file containing position data",
    )

    args = parser.parse_args()

    # Read positions
    print(f"Reading positions from: {args.csv_file}")
    positions = read_positions_from_csv(args.csv_file)
    print(f"Loaded {len(positions)} positions")

    # Play positions
    await play_positions(positions)


if __name__ == "__main__":
    asyncio.run(main())
